config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :chat_rooms, only: [:new, :create, :show, :index]

  root 'chat_rooms#index'

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :users, -> { uniq }, through: :messages
  has_many :messages, -> { order(created_at: :asc) }, dependent: :destroy
end

app/models/dialect.rb
class Dialect < ApplicationRecord
  has_many :users
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room  #TODO add polymorfic

  validates :body, presence: true, length: { minimum: 2, maximum: 1000 }

  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  belongs_to :dialect

  def nickname
      name ? name : email.split('@').first
  end

  def online
    REDIS.sadd("online", self.nickname)
    AppearanceBroadcastJob.perform_later list
  end

  def offline
    REDIS.srem("online", self.nickname)
    AppearanceBroadcastJob.perform_later list
  end

  def list
    REDIS.smembers("online")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    attributes = [:dialect_id]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def index
    @chat_rooms = ChatRoom.all
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
    @users = @chat_room.users.where.not(id: current_user.id)
    @appearances = []
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  private
  #########################################################################

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chat_rooms/_chat_room.html.slim
.li
  = link_to "Enter #{chat_room.title}", chat_room_path(chat_room)

app/views/chat_rooms/_form.html.slim
.panel-footer
  = form_for @message, url: '#' do |f|
    .form-group
      = f.text_area :body, class: 'form-control'
      small.text-muted From 2 to 1000 characters

    .form-group
      = f.submit "Post", class: 'btn btn-success'

app/views/chat_rooms/_user_list.html.slim
ul
  - list.each do |user|
    li.clearfix
      .about
        .status
          i.fa.fa-circle.online
          | online 
        .name = user

app/views/chat_rooms/index.html.slim
.title
  h2 Chat rooms

  p.lead
    = link_to 'New chat room', new_chat_room_path, class: 'btn btn-success'

  .shared-links
    .ul
      = render @chat_rooms

app/views/chat_rooms/new.html.slim
h2.title Add Chat Room

= form_for @chat_room do |f|
  .form-group
    = f.label :title
    = f.text_field :title, autofocus: true, class: 'form-control'

  .form-group
    = f.submit "Add!", class: 'btn btn-success'

app/views/chat_rooms/show.html.slim
.clearfix
  .row
    .col-md-9
      .chat
        .chat-header.clearfix
          .chat-about
            .chat-with Chat "#{@chat_room.title}"
            .chat-num-messages Your dialect is "#{current_user.dialect.name}"
          i.fa.fa-star
        .chat-history
          #messages data-chat-room-id="#{@chat_room.id}"
            ul
              = render @chat_room.messages
        .chat-message.clearfix
          = render 'form'
    .col-md-3
      #people-list.people-list

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-fixed-top.navbar-inverse.bg-inverse
	.container-fluid
    .navbar-header
      = link_to 'MESSENGER', root_path, class: 'navbar-brand'

    - if current_user.present?
      .navbar-nav.pull-right
        a.dropdown-toggle data-toggle="dropdown" href="#" 
          = image_tag current_user.dialect.image, class: 'avatar-icon'
          = current_user.nickname
        span.caret
        ul.dropdown-menu
          li
            = link_to 'Sign out', destroy_user_session_path, method: :delete
          li
            = link_to 'Edit Account', edit_user_registration_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messanger</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.slim
li
  .message-data
    span.message-data-name
      = image_tag message.user.dialect.image, class: 'avatar-icon'
      = message.user.nickname
    span.message-data-time = message.timestamp
  .message.my-message
    = message.body